name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'gradle'
      - name: Check Gradle Version
        run: |
          chmod +x gradlew
          ./gradlew --version
      - name: Test task with Gradle Wrapper
        run: |
          ./gradlew test
